### PR TITLE
get*ExchangeRate always returns an object

### PR DESCRIPTION
**Pull request by szepeviktor**
cannot be falsy

https://travis-ci.org/github/florianv/exchanger/builds/738295141 👀

### CODE REVIEW

**Comment by szepeviktor** [comment]
Is a there a test that should throw `UnsupportedCurrencyPairException`??

**Comment by florianv** [comment]
@szepeviktor Indeed, the code can be simplified. Your PR fails because of the code style, but the tests seem to pass

**Comment by szepeviktor** [comment]
Done.

**Comment by florianv** [comment]
Thanks @szepeviktor ! I merged your changes without the comment removal (CS was failing).

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request closed without merging**
