### PR TITLE
Update Forge service to use new rest API url.

### PR DESCRIPTION
**Pull request by leeovery**
Old one is being sunsetted in 3 days. The new url is up and working now so this is a none breaking change.

### CODE REVIEW

**Comment by florianv** [comment]
@leeovery Can you please update the tests too ?

**Comment by leeovery** [comment]
@florianv sorry about that!! All done.

**Comment by SouD** [comment]
@leeovery I think you might have included your `.idea` folder in the PR.

**Comment by leeovery** [comment]
> @leeovery I think you might have included your `.idea` folder in the PR.

Thanks!! Removed

**Comment by leeovery** [comment]
@florianv The old forge endpoint is being shut off in a few hours. Any chance we can merge this? Thank you!!

**Comment by florianv** [comment]
@leeovery Can you please remove the `.idea` files ? Thanks!

**Comment by leeovery** [comment]
@florianv I already removed them. I done it 3 days ago :)

**Comment by kubrat** [comment]
Hi @florianv. Could we have this applied to the `1.x` too?

Also, what's the difference between versions `1.x` and `2`?

**Pull request merged**
