### PR TITLE
Rename CurrencyConverterApi into CurrencyConverter (#78)

### PR DESCRIPTION
**Pull request by lptn**
Patch version of the https://github.com/florianv/exchanger/pull/79 fix, but for 1.X branch (most likely 1.3.1 version)

### CODE REVIEW

**Comment by florianv** [comment]
Thanks for your PR @lptn 👍 

Can you please fix the tests and I will merge ? Should be just due to the rename.

**Comment by lptn** [comment]
@florianv 
Sure. Sorry for asking for review of broken code. I didn't manage to run tests on my local machine using `composer test`: got `PHP Fatal error:  Uncaught Error: Class 'PHPUnit_Framework_TestCase' not found in /Users/**/exchanger/tests/Tests/CurrencyPairTest.php:16` error. Probably because of old phpunit version (but it didn't work even when I specified `--bootstrap vendor/autoload.php` explicitly)

**Comment by florianv** [comment]
@lptn thanks for your pull request.

PHPUnit is installed with this library in development mode.

I think you should run the tests using `vendor/bin/phpunit` instead of `phpunit` to use the correct version.

**Comment by lptn** [comment]
>I think you should run the tests using `vendor/bin/phpunit` instead of `phpunit` to use the correct version.
>There is also a `composer test` alias in the `composer.json`.

Yes, I saw them, but they don't work for some reason on my end (I've reinstalled composer dependencies).

```sh
 ./vendor/bin/phpunit --version 
# PHPUnit 7.5.1 by Sebastian Bergmann and contributors.

 ./vendor/bin/phpunit --bootstrap vendor/autoload.php
# PHP Fatal error:  Uncaught Error: Class 'PHPUnit_Framework_TestCase' not found in /Users/*/exchanger/tests/Tests/CurrencyPairTest.php:16

composer test
# Fatal error: Uncaught Error: Class 'PHPUnit_Framework_TestCase' not found in /Users/*/exchanger/tests/Tests/CurrencyPairTest.php:16
```

However everything works fine on master branch (what is more important 👍).

**Pull request merged**
