### PR TITLE
[BUG] Exchange Rates API no longer working

### PR DESCRIPTION
**Pull request by srishaharidas**

### CODE REVIEW

**Comment by florianv** [comment]
Thanks @srishaharidas :)

**Comment by lptn** [comment]
This is a braking change unfortunately: it requires to update app config

**Comment by florianv** [comment]
@lptn Do you have an example? I understand it like the API is broken anyway without the `access_key`

**Comment by srishaharidas** [comment]
> @lptn Do you have an example? I understand it like the API is broken anyway without the `access_key`

Yes this is what I was seeing as well. Currently the Exchange Rates API isnt working at all without an access key so I thought it does make sense for it be required.

**Comment by lptn** [comment]
@florianv  the package usually throws \Exchanger\Exception exceptions, but in this case it throws something unexpected:

```
"class": "InvalidArgumentException",
"message": "The \"access_key\" option must be provided to use exchangeratesapi.io",
"code": 0,
"file": "/vendor/florianv/exchanger/src/Service/ExchangeRatesApi.php:46",
"trace": [
"/vendor/florianv/exchanger/src/Service/Service.php:41",
"/vendor/florianv/exchanger/src/Service/HttpService.php:63",
"/vendor/florianv/swap/src/Service/Factory.php:116",
"/vendor/florianv/swap/src/Builder.php:169",
"/vendor/florianv/laravel-swap/src/SwapServiceProvider.php:64",
"/vendor/laravel/framework/src/Illuminate/Container/Container.php:829",
```

If we allow script to silently fail (with old unsupported config) - it’s not a breaking change. But it throws `\ InvalidArgumentException` and requires to change config files manually.

**Comment by florianv** [comment]
@lptn Indeed, that's a nice catch. Sorry for that.

I just introduced a new `Exception` that we can use for those cases: when the service breaks BC with a new parameter.

So the exception chain is not broken.

**Pull request merged**
